### ISSUE TITLE
Paradigm tables fill whole page width

### ISSUE THREAD

**Issue by fmatter** [clld/cariban#6]
They are auto-width on my local machine, so I can't test potential fixes.

**Comment by fmatter** [comment]
See example [here](https://cariban.clld.org/construction/aku_main).

**Comment by xrotwang** [comment]
Was fixed here https://github.com/clld/clld/commit/addf0dc1629ce9ae457953d03c42ba8bbd9ed368 and released with clld 7.4.1. Upgrading clld on the server fixed the problem.
